### ISSUE TITLE
gen_check_code(32 bit)

### ISSUE THREAD

**Issue by realmcu** [loboris/OrangePI-Kernel#13]
Dear loboris,
       I got a Orange PI PC board, I want build linux kernel myself , but there is a error when call gen_check_code elf(64 bit) 
       my PC is ubuntu 32 bit, could you give me gen_check_code source code. Or tell me  other way to solve this issue.

**Comment by ThomasKaiser** [comment]
Have a look at https://github.com/loboris/OrangePI-Kernel/pull/3 instead. And if that works for you (there's no alternative ;-) think about closing the issue.

**Comment by realmcu** [comment]
yes,thank you!
